version: 2.1


jobs:
  test:
    docker:
    - image: golang:1.17.5-alpine3.15
    working_directory: /go/src/github.com/hiromu-saito/trip-note-backend/api
    environment:
      GOPATH: /
      GOCACHE: /.cache/go-build
      GO111MODULE: "on"

    steps:
      - checkout
      - run: "test start!"
      - run: go test ./...

workflows:
  version: 2
  test:
    jobs:
      - test
  
