version: 2.1


jobs:
  test:
    docker:
    - image: golang:1.17.5-alpine3.15
    working_directory: /go/src/github.com/hiromu-saito/trip-note-backend
    environment:
      GOPATH: /
      GOCACHE: /.cache/go-build
      GO111MODULE: "on"

    steps:
      - checkout
      - run: "test start!"
      - run : pwd
      - run : ls -la ./api
      - run : cd api
      - run : ls -la 
      - run : 
          command: go get
          name: go get
          working_directory: /go/src/github.com/hiromu-saito/trip-note-backend/api 
      - run:
          command: go test ./...
          working_directory: /go/src/github.com/hiromu-saito/trip-note-backend/api 

workflows:
  version: 2
  test:
    jobs:
      - test
  
